### ISSUE TITLE
not require all libs

### ISSUE THREAD

**Issue by fooelisa** [spotify/napalm#13]
but selected ones as plugins
^ suggestion from grizz

**Comment by dbarrosop** [comment]
And what would be the benefit of that? We are talking about libraries that each need a couple of KB in your disk and that are loaded as you need them. Turning this into plugins will just make things harder from a development point of view (specially unittests) for no apparent gain.

**Comment by fooelisa** [comment]
are plugins hard? I have no idea. Figured it would be nice not to have to install all that juniper stuff if I had an arista only network eg

**Comment by dbarrosop** [comment]
I am not sure what you mean by plugins. if you mean different libraries that implement napalm basic functionality that will grow hard to maintain. Unittests not run in a unified manner, libraries diverging from the main napalm base... Etc. if you mean something else let me know.
