### ISSUE TITLE
work with user accounts with ssh keys without passwd

### ISSUE THREAD

**Issue by fooelisa** [spotify/napalm#14]

**Comment by dbarrosop** [comment]
Not sure I want this. Mainly because neither EOS nor IOS XR supports that. And the main principle of napalm is to provide the same user experience for all the vendors.

**Comment by fooelisa** [comment]
there will be more vendors... but uh, no support at all? weird

**Comment by dbarrosop** [comment]
I know and I hope there will be more vendors. But the idea here is to support the same user experience so we have to accommodate to the minimum common denominator. And no, none of those support ssh keys... EOS migh support certificates (eAPI it's https) but that's not ssh keys...

**Comment by zevlag** [comment]
Looks like this was eventually added as optional args.

I found this here: https://github.com/napalm-automation/napalm/blob/master/docs/support/index.rst
>allow_agent (ios, panos) - Paramiko argument, enable connecting to the SSH agent (default: 'False').
>use_keys (ios, panos) - Paramiko argument, enable searching for discoverable private key files in ~/.ssh/ (default: ‘False’).
>key_file (vyos) - Netmiko/Paramiko argument, path to a private key file (default: 'False').
