### ISSUE TITLE
add support for extreme networks devices. 

### ISSUE THREAD

**Issue by ckannan** [spotify/napalm#48]

**Comment by ckannan** [comment]
Like the X670-G2-48x

**Comment by dbarrosop** [comment]
Hello @ckannan,
is this something you would like to work on? I am afraid that:

1. I am not familiar with that device.
2. I don't have any extreme switch to develop/test
3. I don't have time to support devices other than the ones I have in my network.

However, I do have time to help people extending NAPALM and adding support to new devices so if you have time and you want to work on this let me know.

Regards.
David

**Comment by dbarrosop** [comment]
As nobody seems to pick up this task I am going to close it.
